{% set name = "sqlite-minutils" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d391c067b6c88f7a1917c8781fa3924eb2afbbadf06d7b548ac4a551b3e71e72

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.8
    - fastcore

test:
  imports:
    - sqlite_minutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AnswerDotAI/sqlite-minutils
  summary: A fork of sqlite-utils with CLI etc removed
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/AnswerDotAI/sqlite-minutils

extra:
  recipe-maintainers:
    - synapticarbors
