{% set name = "sqlite-minutils" %}
{% set version = "3.37.0.post3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d7f8db1581ef4e8e6d507ad8998f3c0ad574c507e36715818017108c0814a1e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.7,<4.0
    - fastcore

test:
  imports:
    - sqlite_minutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AnswerDotAI/sqlite-minutils
  summary: A fork of sqlite-utils with CLI etc removed
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/AnswerDotAI/sqlite-minutils

extra:
  recipe-maintainers:
    - synapticarbors
