{% set name = "sqlite-minutils" %}
{% set version = "3.36.0.post4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlite_minutils-{{ version }}.tar.gz
  sha256: 4a44adf3820796e2b0c24b35982c53e687a3a95d7bedbe7859c48cce6616837a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.7,<4.0
    - fastcore

test:
  imports:
    - sqlite_minutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AnswerDotAI/sqlite-minutils
  summary: A fork of sqlite-utils with CLI etc removed
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/AnswerDotAI/sqlite-minutils

extra:
  recipe-maintainers:
    - synapticarbors
