context:
  name: sqlite-minutils
  version: "4.0.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: c3fc6d20f86b2cd0071eaa9e356024ef83aba3ce9d9606e50c4ab255c3279a71

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    # pin setuptools since >=82 drops pgk_resources
    - setuptools >=64.0,<82.0
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - fastcore

tests:
  - python:
      imports:
        - sqlite_minutils
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A fork of sqlite-utils with CLI etc removed
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/AnswerDotAI/sqlite-minutils
  repository: https://github.com/AnswerDotAI/sqlite-minutils

extra:
  recipe-maintainers:
    - synapticarbors
